language: node_js
node_js:
  - 12

env:
  global:
    - DB_CONFIG=test
    - SENDGRID_API_KEY=xyz
    - SESSION_SECRET=any
    - SENDGRID_SENDER='teachermoments@mit.edu'
    - MAILTRAP_USER=foo
    - MAILTRAP_PASS=bar

before_install:
  - export TZ=America/New_York

# addons:
#   postgresql: "11"

# services:
#   - postgresql

before_script:
  # - yarn db-init:test

jobs:
  include:
    - stage: Build
      script:
        - yarn build
    - stage: Client test
      script:
        - yarn workspace client run test
    # - stage: Server test
    #   script:
    #     - yarn workspace server run test
    #     - yarn workspace test run test
